spring:
  profiles:
    active: prod
  data:
    mongodb:
      uri: mongodb://localhost:27017
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便 进行模板测试
  rabbitmq:
    host: 49.234.11.97
    port: 5672
    username: admin
    password: sdgwf3hfDwq!
    virtual-host: /
#  datasource:
#    druid:
#      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
#      username: root
#      password: mysql
#      driverClassName: com.mysql.jdbc.Driver
#      initialSize: 5  #初始建立连接数量
#      minIdle: 5  #最小连接数量
#      maxActive: 20 #最大连接数量
#      maxWait: 10000  #获取连接最大等待时间，毫秒
#      testOnBorrow: true #申请连接时检测连接是否有效
#      testOnReturn: false #归还连接时检测连接是否有效
#      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
#      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
server:
  port: ${PORT:8088} #服务端口
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"
