spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: test
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便 进行模板测试
  rabbitmq:
    host: 127.0.0.1
    port: 5673
    username: guest
    password: guest
    virtual-host: /
server:
  port: 8088 #服务端口
